name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master # Triggers the workflow on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # The 'version' key is removed. The action will now automatically
        # use the version specified in the 'packageManager' field of package.json.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # Use pnpm for caching

      - name: Install Dependencies
        run: pnpm install # Use pnpm to install

      - name: Create .env file for build process
        run: echo "NUXT_SITE_TOKEN=${{ secrets.NUXT_SITE_TOKEN }}" > .env

      - name: Build the Project
        run: pnpm run build # Use the build script from your package.json

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            NUXT_SITE_TOKEN
        env:
          NUXT_SITE_TOKEN: ${{ secrets.NUXT_SITE_TOKEN }}